name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly (adjust as needed)
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4  # Ensure to use the latest version of checkout

      - name: Set up Python
        uses: actions/setup-python@v3  # Use the latest version of setup-python
        with:
          python-version: '3.10.12'  # Specify Python version (adjust as needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required packages, including smtplib and BeautifulSoup

      - name: Run the script
        env:
          EMAIL: ${{ secrets.EMAIL }}  # Use the stored secret for email
          PASSWORD: ${{ secrets.PASSWORD }}  # Use the stored secret for password
        run: |
          python angle_email.py  # Run the script using Python
