name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly (adjust as needed)
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version (adjust as needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required packages, including smtplib and BeautifulSoup

      - name: Run the script
        env:
          EMAIL: ${{ secrets.EMAIL }}  # Use the stored secret for email
          PASSWORD: ${{ secrets.PASSWORD }}  # Use the stored secret for password
        run: |
          angle_email.py  # Replace with your actual script filename
